// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type CreateTenantReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type CreateTenantResp struct {
	TenantID uint64 `json:"tenant_id"`
}

type CreateUserReq struct {
	UserName  string   `json:"user_name"`  // 用户名
	Name      string   `json:"name"`       // 姓名
	Phone     string   `json:"phone"`      // 手机号
	Email     string   `json:"email"`      // 邮箱
	PwdHashed string   `json:"pwd_hashed"` // 密码哈希
	PwdSalt   string   `json:"pwd_salt"`   // 密码盐值
	Status    int      `json:"status"`     // 状态
	Sex       int      `json:"sex"`        // 性别
	Avatar    string   `json:"avatar"`     // 头像
	RoleIDs   []uint64 `json:"role_ids"`   // 角色ID列表
}

type CreateUserResp struct {
	UserID uint64 `json:"user_id"` // 用户ID
}

type DeleteTenantReq struct {
	TenantID uint64 `path:"tenant_id"`
}

type DeleteUserReq struct {
	UserID uint64 `path:"user_id"`
}

type GetTenantReq struct {
	TenantID uint64 `path:"tenant_id" `
}

type GetTenantResp struct {
	TenantInfo
}

type GetUserReq struct {
	UserID uint64 `path:"user_id"`
}

type GetUserResp struct {
	UserInfo
}

type IDRequest struct {
	ID int `json:"id"` // ID
}

type ListTenantReq struct {
	PageRequest
	Status int `form:"status,optional"` // 状态
}

type ListTenantResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*TenantInfo `json:"list"` // 租户列表
}

type LoginReq struct {
	UserName string `json:"username" validate:"required"` // 用户名
	Password string `json:"password" validate:"required"` // 密码
}

type LoginResp struct {
	Token    string `json:"token"`
	UserID   uint64 `json:"user_id"`
	UserName string `json:"user_name"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}

type LogoutReq struct {
	UserID uint64 `json:"user_id"`
}

type PageJsonRequest struct {
	Current  int `json:"current"`   // 当前页
	PageSize int `json:"page_size"` // 每页大小
}

type PageRequest struct {
	Current  int `form:"page,default=1" validate:"required,gte=1"`               // 当前页
	PageSize int `form:"page_size,default=10" validate:"required,gte=1,lte=100"` // 每页大小
}

type PageResponse struct {
	Total           int `json:"total"`             // 总数
	PageSize        int `json:"page_size"`         // 当前页大小
	RequestPageSize int `json:"request_page_size"` // 请求页大小
	Current         int `json:"current"`           // 当前页
}

type RegisterReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	NickName string `json:"nick_name"`
	Avatar   string `json:"avatar,optional"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	Sex      int    `json:"sex,optional"`
}

type RegisterResp struct {
	UserID uint64 `json:"user_id"`
}

type StatusRequest struct {
	ID     int `json:"id"`     // ID
	Status int `json:"status"` // 状态
}

type TenantInfo struct {
	TenantID    uint64 `json:"tenant_id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int    `json:"status"`
}

type TimeRange struct {
	StartTime string `form:"start_time,optional"` // 开始时间
	EndTime   string `form:"end_time,optional"`   // 结束时间
}

type UpdateTenantReq struct {
	TenantID    uint64 `path:"tenant_id" `
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int    `json:"status"`
}

type UpdateUserReq struct {
	UserID  uint64   `path:"user_id"`
	Name    string   `json:"name,optional"`
	Phone   string   `json:"phone,optional"`
	Email   string   `json:"email,optional"`
	Status  int      `json:"status,optional"`
	Sex     int      `json:"sex,optional"`
	Avatar  string   `json:"avatar,optional"`
	RoleIDs []uint64 `json:"role_ids,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`    // 用户ID
	UserName  string `json:"user_name"`  // 用户名
	Name      string `json:"name"`       // 姓名
	Phone     string `json:"phone"`      // 手机号
	Email     string `json:"email"`      // 邮箱
	Avatar    string `json:"avatar"`     // 头像
	Status    int    `json:"status"`     // 状态
	CreatedAt string `json:"created_at"` // 创建时间
}

type UserListReq struct {
	PageRequest
	Name   string `form:"name,optional"`   // 姓名
	Phone  string `form:"phone,optional"`  // 手机号
	Status int    `form:"status,optional"` // 状态
}

type UserListResp struct {
	Page *PageResponse `json:"page"` // 分页
	List []*UserInfo   `json:"list"` // 用户列表
}
