// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type CreateUserReq struct {
	No                  string `json:"no"`
	Name                string `json:"name"`
	Phone               string `json:"phone"`
	Role                int    `json:"role"`
	PwdHashed           string `json:"pwd_hashed"`
	PwdSalt             string `json:"pwd_salt"`
	DisableStatus       int    `json:"disable_status"`
	ParentDisableStatus int    `json:"parent_disable_status"`
	Company             string `json:"company"`
	Email               string `json:"email"`
	Gender              int    `json:"gender"`
	Icon                string `json:"icon"`
	RoleIDs             []int  `json:"roleIDs"` // 角色ID列表
}

type CreateUserResp struct {
	ID int `json:"id"`
}

type DeleteUserReq struct {
	Id int `path:"id"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetUserReq struct {
	Id int `path:"id"`
}

type GetUserResp struct {
	UserInfoResponse
}

type IDRequest struct {
	ID int `json:"id"` // ID
}

type PageJsonRequest struct {
	Current  int32 `json:"current"`   // 当前页
	PageSize int32 `json:"page_size"` // 每页大小
}

type PageRequest struct {
	Current  int32 `json:"current"`   // 当前页
	PageSize int32 `json:"page_size"` // 每页大小
}

type PageResponse struct {
	Total           int32 `json:"total"`             // 总数
	PageSize        int32 `json:"page_size"`         // 当前页大小
	RequestPageSize int32 `json:"request_page_size"` // 请求页大小
	Current         int32 `json:"current"`           // 当前页
}

type StatusRequest struct {
	ID     int `json:"id"`     // ID
	Status int `json:"status"` // 状态
}

type TimeRange struct {
	StartTime string `form:"start_time,optional"` // 开始时间
	EndTime   string `form:"end_time,optional"`   // 结束时间
}

type UpdateUserReq struct {
	Id   int    `path:"id"`
	Name string `json:"name"`
}

type UpdateUserResp struct {
	Success bool `json:"success"`
}

type UserInfoResponse struct {
	ID          int    `json:"id"`           // 用户id
	Uid         int    `json:"uid"`          // 用户id
	Name        string `json:"name"`         // 企业名称
	No          string `json:"no"`           // 企业编号
	Phone       string `json:"phone"`        // 企业号码
	StartAt     string `json:"start_at"`     // 合作开始时间
	EndAt       string `json:"end_at"`       // 合作结束时间
	Email       string `json:"email"`        // 邮箱
	Province    string `json:"province"`     // 所在省份
	City        string `json:"city"`         // 所在地区
	Address     string `json:"address"`      // 具体地址
	CompanyDesc string `json:"company_desc"` // 企业介绍
	Status      int    `json:"status"`       // 状态
	RoleIDs     []int  `json:"roleIDs"`      // 角色ID列表
}

type UserListReq struct {
	PageRequest
	Name   string `form:"name,optional"`
	Phone  string `form:"phone,optional"`
	Status int    `form:"status,optional"`
}

type UserListResp struct {
	Page *PageResponse       `json:"page"` // 分页
	List []*UserInfoResponse `json:"list"` // 列表
}
