// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	user "github.com/solate/admin_backend/app/admin/internal/handler/user"
	"github.com/solate/admin_backend/app/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建用户
					Method:  http.MethodPost,
					Path:    "/",
					Handler: user.CreateHandler(serverCtx),
				},
				{
					// 获取用户列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: user.ListHandler(serverCtx),
				},
				{
					// 删除用户
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: user.DeleteHandler(serverCtx),
				},
				{
					// 更新用户
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: user.UpdateHandler(serverCtx),
				},
				{
					// 获取用户详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: user.GetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/api/v1/user"),
	)
}
